### ISSUE TITLE
should rewrite readme (section: If you are babel(JSX) user)

### ISSUE THREAD

**Issue by kubosho** [yosuke-furukawa/eater#19]
Maybe remove `power-assert and babel user` note. Because `espower-babel` is deprecated. 

https://github.com/power-assert-js/espower-babel#warning-deprecated-warning
http://efcl.info/2016/04/14/espower-babel-is-deprecated/

**Comment by yosuke-furukawa** [comment]
Yep, I also know that.
I will re-write the section to use `babel-preset-power-assert`.

https://github.com/power-assert-js/babel-preset-power-assert

**Comment by yosuke-furukawa** [comment]
I created this issue, https://github.com/yosuke-furukawa/eater/issues/20
I will update my README.md, if I will change, PTAL.
